# Generated by Django 3.0.3 on 2020-09-27 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200923_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('archive', models.CharField(choices=[('Creature of Comfort', 'Creature of Comfort'), ('Protector of Habit', 'Protector of Habit'), ('Navigator of Discomfort', 'Navigator of Discomfort'), ('Pioneer of Curiosity', 'Pioneer of Curiosity'), ('Challenger of Norms', 'Challenger of Norms'), ('Bastion of Cohesion', 'Bastion of Cohesion')], max_length=200, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
