# Generated by Django 3.0.3 on 2020-09-27 23:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200927_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
